#Write a program to input eight numbers from the user and display all the unique numbers(once).
num= set()
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
n=int(input("Enter numbers:"))
num.add(n)
print(num)